/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */

import {
  EventHandler,
  EventHandlerOptions,
  EventManager,
  hasModifiers,
  ModifierInputs,
  Modifier,
} from './event-manager';

/**
 * An event manager that is specialized for handling click events.
 *
 * This manager should ONLY be used to handle pointer events. It explicitly
 * filters out simulated click events generated by browsers when Enter or Space
 * keys are pressed, to avoid concurrent logic or overwriting selection state
 * when handling keyboard activation explicitly via KeyboardEventManager.
 */
export class ClickEventManager<T extends PointerEvent> extends EventManager<T> {
  options: EventHandlerOptions = {
    preventDefault: false,
    stopPropagation: false,
  };

  /**
   * Configures this event manager to handle events with a specific modifier combination.
   */
  on(modifiers: ModifierInputs, handler: EventHandler<T>): this;

  /**
   * Configures this event manager to handle events with no modifiers.
   *
   * @param handler The handler function
   */
  on(handler: EventHandler<T>): this;

  on(...args: unknown[]) {
    const {handler, modifiers} = this._normalizeInputs(...args);

    this.configs.push({
      handler,
      matcher: event => this._isMatch(event, modifiers),
      ...this.options,
    });
    return this;
  }

  private _normalizeInputs(...args: unknown[]) {
    if (args.length === 2) {
      return {
        modifiers: args[0] as ModifierInputs,
        handler: args[1] as EventHandler<T>,
      };
    }

    return {
      modifiers: Modifier.None,
      handler: args[0] as EventHandler<T>,
    };
  }

  _isMatch(event: T, modifiers: ModifierInputs) {
    return this._isRealClick(event) && hasModifiers(event, modifiers);
  }

  /**
   * Checks if the event is a "real" pointer click.
   *
   * Real clicks typically have a non-zero detail count (click count) and
   * a valid pointerType (e.g. 'mouse' or 'touch').
   */
  private _isRealClick(event: T): boolean {
    if (event.detail === 0) return false;
    if (event.clientX === 0 && event.clientY === 0) return false;
    if (!event.pointerType) return false;
    return true;
  }
}
