packages:
  - .
  - docs
  - integration
  - src/cdk
  - src/cdk-experimental
  - src/components-examples
  - src/dev-app
  - src/e2e-app
  - src/google-maps
  - src/material
  - src/material-date-fns-adapter
  - src/material-experimental
  - src/material-luxon-adapter
  - src/material-moment-adapter
  - src/universal-app
  - src/youtube-player

catalog:
  '@angular-devkit/build-angular': 20.2.0-rc.0
  '@angular-devkit/core': 20.2.0-rc.0
  '@angular-devkit/schematics': 20.2.0-rc.0
  '@angular/animations': 20.2.0-rc.1
  '@angular/build': 20.2.0-rc.0
  '@angular/cli': 20.2.0-rc.0
  '@angular/common': 20.2.0-rc.1
  '@angular/compiler-cli': 20.2.0-rc.1
  '@angular/compiler': 20.2.0-rc.1
  '@angular/core': 20.2.0-rc.1
  '@angular/ssr': 20.2.0-rc.0
  '@angular/forms': 20.2.0-rc.1
  '@angular/localize': 20.2.0-rc.1
  '@angular/platform-browser': 20.2.0-rc.1
  '@angular/platform-browser-dynamic': 20.2.0-rc.1
  '@angular/platform-server': 20.2.0-rc.1
  '@angular/router': 20.2.0-rc.1
  '@schematics/angular': 20.2.0-rc.0
  'rxjs': ^6.6.7
