packages:
  - .
  - docs
  - integration
  - src/aria
  - src/cdk
  - src/cdk-experimental
  - src/components-examples
  - src/dev-app
  - src/e2e-app
  - src/google-maps
  - src/material
  - src/material-date-fns-adapter
  - src/material-experimental
  - src/material-luxon-adapter
  - src/material-moment-adapter
  - src/universal-app
  - src/youtube-player

catalog:
  '@angular-devkit/build-angular': 21.0.5
  '@angular-devkit/core': 21.0.5
  '@angular-devkit/schematics': 21.0.5
  '@angular/build': 21.0.5
  '@angular/cli': 21.0.5
  '@angular/common': 21.0.8
  '@angular/compiler-cli': 21.0.8
  '@angular/compiler': 21.0.8
  '@angular/core': 21.0.8
  '@angular/ssr': 21.0.5
  '@angular/forms': 21.0.8
  '@angular/localize': 21.0.8
  '@angular/platform-browser': 21.0.8
  '@angular/platform-browser-dynamic': 21.0.8
  '@angular/platform-server': 21.0.8
  '@angular/router': 21.0.8
  '@schematics/angular': 21.0.5
  'rxjs': ^6.6.7

# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440
# List of packages to exclude from the minimum release age check.
minimumReleaseAgeExclude:
  - '@angular-devkit/*'
  - '@angular/*'
  - '@ngtools/webpack'
  - '@schematics/*'
  - 'ng-packagr'
