packages:
  - .
  - docs
  - integration
  - src/aria
  - src/cdk
  - src/cdk-experimental
  - src/components-examples
  - src/dev-app
  - src/e2e-app
  - src/google-maps
  - src/material
  - src/material-date-fns-adapter
  - src/material-experimental
  - src/material-luxon-adapter
  - src/material-moment-adapter
  - src/universal-app
  - src/youtube-player

catalog:
  '@angular-devkit/build-angular': 22.1.0-next.1
  '@angular-devkit/core': 22.1.0-next.1
  '@angular-devkit/schematics': 22.1.0-next.1
  '@angular/build': 22.1.0-next.1
  '@angular/cli': 22.1.0-next.1
  '@angular/common': 22.1.0-next.3
  '@angular/compiler-cli': 22.1.0-next.3
  '@angular/compiler': 22.1.0-next.3
  '@angular/core': 22.1.0-next.3
  '@angular/ssr': 22.1.0-next.1
  '@angular/forms': 22.1.0-next.3
  '@angular/localize': 22.1.0-next.3
  '@angular/platform-browser': 22.1.0-next.3
  '@angular/platform-browser-dynamic': 22.1.0-next.3
  '@angular/platform-server': 22.1.0-next.3
  '@angular/router': 22.1.0-next.3
  '@schematics/angular': 22.1.0-next.1
  'rxjs': ^6.6.7

# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440
# List of packages to exclude from the minimum release age check.
minimumReleaseAgeExclude:
  - '@angular-devkit/*'
  - '@angular/*'
  - '@ngtools/webpack'
  - '@schematics/*'
  - 'ng-packagr'
overrides:
  typescript: 6.0.2
  protobufjs: 8.6.5
packageExtensions:
  dgeni-packages:
    dependencies:
      clonedeep: '*'
  grpc-gcp:
    dependencies:
      protobufjs: 7.4.0
  '@angular-eslint/eslint-plugin-template@19.3.0':
    peerDependencies:
      '@typescript-eslint/parser': '*'
      '@angular-eslint/template-parser': '*'
  '@angular/common':
    dependencies:
      '@nginfra/angular-linking': 1.0.11
  '@angular/forms':
    dependencies:
      '@nginfra/angular-linking': 1.0.11
  '@angular/platform-browser':
    dependencies:
      '@nginfra/angular-linking': 1.0.11
  '@angular/router':
    dependencies:
      '@nginfra/angular-linking': 1.0.11
  '@angular/localize':
    dependencies:
      '@nginfra/angular-linking': 1.0.11
  '@angular/platform-server':
    dependencies:
      '@nginfra/angular-linking': 1.0.11
engineStrict: false
hoist: false
autoInstallPeers: false

# Avoid prompting for confirmation when pnpm determines node_modules needs to be purged and recreated.
confirmModulesPurge: false

allowBuilds:
  '@firebase/util': false
  '@google/genai': false
  '@parcel/watcher': false
  bufferutil: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  protobufjs: false
  re2: false
  utf-8-validate: false
