packages:
  - .
  - docs
  - integration
  - src/cdk
  - src/cdk-experimental
  - src/components-examples
  - src/dev-app
  - src/e2e-app
  - src/google-maps
  - src/material
  - src/material-date-fns-adapter
  - src/material-experimental
  - src/material-luxon-adapter
  - src/material-moment-adapter
  - src/universal-app
  - src/youtube-player

catalog:
  '@angular-devkit/build-angular': 21.0.0-next.0
  '@angular-devkit/core': 21.0.0-next.0
  '@angular-devkit/schematics': 21.0.0-next.0
  '@angular/build': 21.0.0-next.0
  '@angular/cli': 21.0.0-next.0
  '@angular/common': 21.0.0-next.0
  '@angular/compiler-cli': 21.0.0-next.0
  '@angular/compiler': 21.0.0-next.0
  '@angular/core': 21.0.0-next.0
  '@angular/ssr': 21.0.0-next.0
  '@angular/forms': 21.0.0-next.0
  '@angular/localize': 21.0.0-next.0
  '@angular/platform-browser': 21.0.0-next.0
  '@angular/platform-browser-dynamic': 21.0.0-next.0
  '@angular/platform-server': 21.0.0-next.0
  '@angular/router': 21.0.0-next.0
  '@schematics/angular': 21.0.0-next.0
  'rxjs': ^6.6.7
