'use strict';var k=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.m=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var l=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,l);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};k(l,Error);var m=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")};var n=function(a,b){b.unshift(a);l.call(this,m.apply(null,b));b.shift()};k(n,l);var p=function(a,b,c){if(!a){var d="Assertion failed";if(b)var d=d+(": "+b),e=Array.prototype.slice.call(arguments,2);throw new n(""+d,e||[]);}};var aa=Array.prototype.map?function(a,b,c){p(null!=a.length);return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f="string"==typeof a?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};var ba=function(a){return aa(a,function(a){a=a.toString(16);return 1<a.length?a:"0"+a}).join("")};var ca=function(){this.c=-1};var r=function(){this.c=-1;this.c=64;this.a=[];this.j=[];this.l=[];this.h=[];this.h[0]=128;for(var a=1;a<this.c;++a)this.h[a]=0;this.i=this.g=0;this.reset()};k(r,ca);r.prototype.reset=function(){this.a[0]=1732584193;this.a[1]=4023233417;this.a[2]=2562383102;this.a[3]=271733878;this.a[4]=3285377520;this.i=this.g=0};
var t=function(a,b,c){c||(c=0);var d=a.l;if("string"==typeof b)for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.a[0];c=a.a[1];for(var g=a.a[2],h=a.a[3],C=a.a[4],q,e=0;80>e;e++)40>e?20>e?(f=h^c&(g^h),q=1518500249):(f=c^g^h,q=1859775393):60>e?(f=c&g|h&(c|g),q=2400959708):(f=c^g^h,q=
3395469782),f=(b<<5|b>>>27)+f+C+q+d[e]&4294967295,C=h,h=g,g=(c<<30|c>>>2)&4294967295,c=b,b=f;a.a[0]=a.a[0]+b&4294967295;a.a[1]=a.a[1]+c&4294967295;a.a[2]=a.a[2]+g&4294967295;a.a[3]=a.a[3]+h&4294967295;a.a[4]=a.a[4]+C&4294967295};
r.prototype.update=function(a,b){if(null!=a){void 0===b&&(b=a.length);for(var c=b-this.c,d=0,e=this.j,f=this.g;d<b;){if(0==f)for(;d<=c;)t(this,a,d),d+=this.c;if("string"==typeof a)for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.c){t(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.c){t(this,e);f=0;break}}this.g=f;this.i+=b}};
r.prototype.digest=function(){var a=[],b=8*this.i;56>this.g?this.update(this.h,56-this.g):this.update(this.h,this.c-(this.g-56));for(var c=this.c-1;56<=c;c--)this.j[c]=b&255,b/=256;t(this,this.j);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.a[c]>>d&255,++b;return a};/*

 Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var u={32:" ",48:")",49:"!",50:"@",51:"#",52:"$",53:"%",54:"^",55:"&",56:"*",57:"(",186:":",187:"+",188:"<",189:"_",190:">",191:"?",192:"~",219:"{",220:"\\",221:"]",222:'"'},v={32:" ",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",106:"*",107:"+",109:"-",110:".",111:"/",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"`",219:"[",220:"|",221:"}",222:"'"},w=function(a){this.f=!1;this.b=a||"";Object.defineProperty(this,"length",{get:function(){return this.b.length}})};
w.prototype.event=function(a,b){if(65<=a&&90>=a){a=String.fromCharCode(a);if(!b&&!this.f||b&&this.f)a=a.toLowerCase();this.b+=a}else 48<=a&&57>=a&&!b?this.b+=String.fromCharCode(a):20==a?this.f=!this.f:8==a?this.b=this.b.slice(0,-1):b?a in u&&(this.b+=u[a]):a in v&&(this.b+=v[a])};w.prototype.clear=function(){this.b=""};w.prototype.trim=function(a){this.b.length>a&&(this.b=this.b.slice(-1*a))};w.prototype.substr=function(a){return this.b.substr(a)};/*

 Copyright 2011 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var x,y,z,A,B,D=0,E={},F={hash:"",otpCount:0,otpMode:!1,otpTime:null,typed:new w,typedTime:null},G={hash:"",otpCount:0,otpMode:!1,otpTime:null,typed:"",typedTime:null},H=!1,I=!1,J="",K="",L=!1,M=!1,da=function(a){console.log("Inject content scripts into all tabs.");chrome.tabs.query({},function(b){for(var c=0;c<b.length;c++)0!=b[c].url.lastIndexOf("chrome",0)&&chrome.tabs.executeScript(b[c].id,{file:"content_script_compiled.js"});a()})},N=function(){chrome.notifications.getAll(function(a){a.initialize_password_notification?
chrome.notifications.update("initialize_password_notification",{priority:2},function(){}):(a={type:"basic",priority:1,title:chrome.i18n.getMessage("extension_name"),message:chrome.i18n.getMessage("initialization_message"),iconUrl:chrome.extension.getURL("logo_password_alert.png"),buttons:[{title:chrome.i18n.getMessage("sign_in")}]},chrome.notifications.create("initialize_password_notification",a,function(){}),a=function(a){"initialize_password_notification"===a&&chrome.tabs.create({url:"https://accounts.google.com/ServiceLogin?continue=https://www.google.com"})},
chrome.notifications.onClicked.addListener(a),chrome.notifications.onButtonClicked.addListener(a))})},P=function(){if(!H||y)-1!=navigator.appVersion.indexOf("Macintosh")?setTimeout(N,5E3):N(),setTimeout(function(){localStorage.hasOwnProperty("salt")||(console.log("Password still has not been initialized.  Start the password initialization process again."),O(5,1E3,P))},3E5)},O=function(a,b,c){L&&M?c():0<a?setTimeout(function(){O(a-1,2*b,c)},b):console.log("Password is not ready to be initialized.")},
fa=function(){M=!0;Q();chrome.runtime.onMessage.addListener(ea);chrome.identity.getProfileUserInfo(function(a){a&&(K=a.email)})},ea=function(a,b,c){if(void 0!==b.tab)switch(a.action){case "handleKeypress":b=b.tab.id;R(a,G);if(13==a.keyCode)G.typed="";else{c=new Date(a.typedTimeStamp);1E4<c-G.typedTime&&(G.typed="");G.typed+=String.fromCharCode(a.keyCode);G.typedTime=c;G.typed.length>A.length&&(G.typed=G.typed.slice(-1*A.length));c=a.keyCode;var d=F.typed;if(65<=c&&90>=c||97<=c&&122>=c){var e=String.fromCharCode(c),
f=d.b.substr(-1);f!=e&&f==(90>=c?e.toLowerCase():e.toUpperCase())&&(d.b=d.b.slice(0,-1)+e,d.f=!d.f)}F.otpMode||S(b,a,G)}break;case "handleKeydown":b=b.tab.id;R(a,F);13==a.keyCode?F.typed.clear():(c=new Date(a.typedTimeStamp),1E4<c-F.typedTime&&F.typed.clear(),F.typed.event(a.keyCode,a.shiftKey),F.typedTime=c,F.typed.trim(A.length),S(b,a,F));break;case "checkString":T(b.tab.id,a,F);break;case "statusRequest":c(JSON.stringify({passwordLengths:A}));break;case "looksLikeGoogle":U(a,ga(),"",!1,"page/");
ha(b.tab.id,a);break;case "deletePossiblePassword":delete E[b.tab.id];break;case "setPossiblePassword":b=b.tab.id;a.email&&a.password&&(8>a.password.length?console.log("password length is shorter than the minimum of 8"):(console.log("Setting possible password for %s, password length of %s",a.email,a.password.length),E[b]={email:a.email,password:V(a.password),length:a.password.length}));break;case "savePossiblePassword":ia(b.tab.id);break;case "getEmail":c(E[b.tab.id].email)}},W=function(a){a.otpMode=
!1;a.otpCount=0;a.otpTime=null;a.hash="";"string"==typeof a.typed?a.typed="":a.typed.clear()},R=function(a,b){if(b.otpMode&&(6E4<new Date-b.otpTime?W(b):48<=a.keyCode&&57>=a.keyCode?b.otpCount++:(32<a.keyCode||0<b.otpCount)&&W(b),6<=b.otpCount)){var c=JSON.parse(localStorage[b.hash]);console.log("OTP TYPED! "+a.url);U(a,c.email,c.date,!0,"password/");W(b)}},S=function(a,b,c){if(8<=c.typed.length)for(var d=1;d<A.length;d++)A[d]&&(b.password=c.typed.substr(-1*d),T(a,b,c))},X=function(a){return"salt"==
localStorage.key(a)?null:JSON.parse(localStorage[localStorage.key(a)])},ia=function(a){var b=E[a];if(b){for(var c=b.email,d=b.password,e=b.length,f=0;f<localStorage.length;f++)(b=X(f))&&b.email==c&&(delete b.email,delete b.date,localStorage[localStorage.key(f)]=JSON.stringify(b));for(var g=[],f=0;f<localStorage.length;f++)b=X(f),!b||"email"in b||g.push(localStorage.key(f));for(f=0;f<g.length;f++)localStorage.removeItem(g[f]);console.log("Saving password for: "+c);b=d in localStorage?JSON.parse(localStorage[d]):
{length:e};b.email=c;b.date=new Date;L&&(H&&!y?L=!1:(c={type:"basic",title:chrome.i18n.getMessage("extension_name"),message:chrome.i18n.getMessage("initialization_thank_you_message"),iconUrl:chrome.extension.getURL("logo_password_alert.png")},chrome.notifications.create("thank_you_notification",c,function(){L=!1})));localStorage[d]=JSON.stringify(b);delete E[a];Q()}},Q=function(){A=[];for(var a=0;a<localStorage.length;a++){var b=X(a);b&&(A[b.length]=!0)}ja()},T=function(a,b,c){var d=new Date;if(!z||
d>=z)z=d.setHours(d.getHours()+1),D=0;D++;if(18E3>=D&&!c.otpMode&&b.password&&(d=V(b.password),localStorage[d])){var e=JSON.parse(localStorage[d]);e.length==b.password.length&&((console.log("PASSWORD TYPED! "+b.url),H)?Z(e.email)&&(console.log("enterprise mode and email matches domain."),U(b,e.email,e.date,!1,"password/"),c.hash=d,c.otpCount=0,c.otpMode=!0,c.otpTime=new Date,Y(b.url,e.email,a)):(c.otpMode=!0,Y(b.url,e.email,a)))}},Y=function(a,b,c){H&&!I||chrome.storage.local.get("allowed_hosts",
function(d){var e=document.createElement("a");e.href=a;e=e.origin;d=d.allowed_hosts;void 0!=d&&d[e]||(d=chrome.extension.getURL("password_warning.html")+"?"+encodeURIComponent(e)+"&"+encodeURIComponent(b)+"&"+c,chrome.tabs.create({url:d}))})},ha=function(a,b){chrome.storage.local.get("phishing_warning_whitelist",function(c){var d=document.createElement("a");d.href=b.url;d=d.origin;c=c.phishing_warning_whitelist;void 0!=c&&c[d]||(c=chrome.extension.getURL("phishing_warning.html")+"?"+a+"&"+encodeURIComponent(b.url||
"")+"&"+encodeURIComponent(d)+"&"+encodeURIComponent(b.securityEmailAddress),chrome.tabs.update({url:c}))})},U=function(a,b,c,d,e){if(H){var f=new XMLHttpRequest;f.open("POST",x+e,!0);f.onreadystatechange=function(){};f.setRequestHeader("X-Same-Domain","true");f.setRequestHeader("Content-Type","application/x-www-form-urlencoded");e=B.split(",")[0];e=e.trim();var g="email="+encodeURIComponent(b)+"&domain="+encodeURIComponent(e)+"&referer="+encodeURIComponent(a.referer||"")+"&url="+encodeURIComponent(a.url||
"")+"&version="+chrome.runtime.getManifest().version;c&&(g+="&password_date="+Math.floor(Date.parse(c)/1E3));d&&(g+="&otp=true");a.looksLikeGoogle&&(g+="&looksLikeGoogle=true");J&&(g+="&domain_auth_secret="+encodeURIComponent(J));chrome.identity.getAuthToken({interactive:!1},function(a){a&&(console.log("Successfully retrieved oauth token."),g+="&oauth_token="+encodeURIComponent(a));console.log("Sending alert to the server.");f.send(g)})}else console.log("Not in enterprise mode, so not sending a report.")},
ga=function(){if(!H)return"";for(var a=0;a<localStorage.length;a++){var b=X(a);if(b&&b.email&&Z(b.email))return b.email}return Z(K)?K:""},Z=function(a){var b=B.split(","),c;for(c in b){var d="@"+b[c].trim(),e=a.length-d.length;if(0<=e&&a.indexOf(d,e)==e)return!0}return!1},V=function(a){var b=new r;b.update(ka());for(var c=[],d=0,e=0;e<a.length;e++){var f=a.charCodeAt(e);128>f?c[d++]=f:(2048>f?c[d++]=f>>6|192:(55296==(f&64512)&&e+1<a.length&&56320==(a.charCodeAt(e+1)&64512)?(f=65536+((f&1023)<<10)+
(a.charCodeAt(++e)&1023),c[d++]=f>>18|240,c[d++]=f>>12&63|128):c[d++]=f>>12|224,c[d++]=f>>6&63|128),c[d++]=f&63|128)}b.update(c);a=b.digest();b=37;for(c=0;c<a.length;c++)8<=b?b-=8:0==b?a[c]=0:(d=4294967040,d>>=b,a[c]&=d,b=0);return ba(a).substr(0,Math.ceil(9.25))},ka=function(){if(!("salt"in localStorage)){var a=new Uint32Array(1);window.crypto.getRandomValues(a);localStorage.salt=a[0].toString()}return localStorage.salt},ja=function(){chrome.tabs.query({},function(a){for(var b=0;b<a.length;b++)chrome.tabs.sendMessage(a[b].id,
JSON.stringify({passwordLengths:A}))})};chrome.runtime.onInstalled.addListener(function(a){"install"==a.reason&&(console.log("New install detected."),L=!0);"install"!=a.reason&&"update"!=a.reason||da(function(){O(5,1E3,P)})});
chrome.storage.onChanged.addListener(function(a,b){if("managed"==b){console.log("Handling changed policies.");for(var c in a)switch(H||(H=!0,console.log("Enterprise mode via updated managed policy.")),b="",a[c].hasOwnProperty("newValue")&&(b=a[c].newValue),c){case "corp_email_domain":B=b.replace(/@/g,"").toLowerCase();break;case "display_user_alert":I=b;break;case "report_url":x=b;break;case "should_initialize_password":y=b;break;case "domain_auth_secret":J=b}}});
chrome.storage.managed.get(function(a){0==Object.keys(a).length?console.log("No managed policy found. Consumer mode."):(console.log("Managed policy found.  Enterprise mode."),B=a.corp_email_domain.replace(/@/g,"").toLowerCase(),I=a.display_user_alert,H=!0,x=a.report_url,y=a.should_initialize_password,J=a.domain_auth_secret);fa()});
