'use strict';var f=this,h=function(a,b){a=a.split(".");var c=f;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]?c[d]:c[d]={}:c[d]=b};var l=function(a){return 0==k.lastIndexOf(a,0)},m=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},n=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},p=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},q=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=1==c?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};var r=function(a,b){this.b=b||"";this.a=a||""},u=/\"/g,w=/\\\"/g,x=/\\/g,y=/\\\\/g,aa=/^[+a-zA-Z0-9_.!#$%&'*\/=?^`{|}~-]+@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9]{2,63}$/;r.prototype.getName=function(){return this.b};r.prototype.toString=function(){var a=this.getName(),a=a.replace(u,""),b;a:{for(b=0;13>b;b++)if(-1!=a.indexOf('()<>@:\\".[],;'[b])){b=!0;break a}b=!1}b&&(a='"'+a.replace(x,"\\\\")+'"');return""==a?this.a:""==this.a?a:a+" <"+this.a+">"};
var z=function(a,b){if('"'!=a.charAt(b))return!1;var c=0;for(--b;0<=b&&"\\"==a.charAt(b);b--)c++;return 0!=c%2};var ba=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;/*

 Copyright 2011 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var A,B,C,D,E,F,G,H,I,J=["One account. All of Google.","Sign in with your Google Account","<title>Sign in - Google Accounts","//ssl.gstatic.com/accounts/ui/logo_2x.png"],K=['<input id="Passwd" name="Passwd" placeholder="Password" class="" type="password">','<input id="Passwd" name="Passwd" type="password" placeholder="Password" class="">','<input id="signIn" name="signIn" class="rc-button rc-button-submit" ','<div class="editpasswdpage main content clearfix">'],L=["accounts.google.com","login.corp.google.com",
"myaccount.google.com"],k="",M="",N=!1,O=!1,P=!1,Q=!1,U=function(){if(P&&Q&&!l("https://accounts.youtube.com/accounts/CheckConnection")){if(A&&l(A)){var a=document.querySelector(B);a?(chrome.runtime.sendMessage({action:"deletePossiblePassword"}),a.addEventListener("submit",ca,!0)):chrome.runtime.sendMessage({action:"savePossiblePassword"})}else if(l("https://accounts.google.com/ChangePassword")){var b;chrome.runtime.sendMessage({action:"getEmail"},function(a){b=a});var c=document.getElementById("gaia_changepasswordform");
c.addEventListener("submit",function(){chrome.runtime.sendMessage({action:"setPossiblePassword",email:b,password:c.Passwd.value})},!0)}else l("https://accounts.google.com/")?l("https://accounts.google.com/SecondFactor")||l("https://accounts.google.com/b/0/VerifiedPhoneInterstitial")||l("https://accounts.google.com/signin/challenge")||l("https://accounts.google.com/signin/privacyreminder")?chrome.runtime.sendMessage({action:"savePossiblePassword"}):(chrome.runtime.sendMessage({action:"deletePossiblePassword"}),
(a=document.getElementById("gaia_loginform"))&&document.getElementById("Email")&&a.addEventListener("submit",da,!0)):l("https://myaccount.google.com/security/signinoptions/password")?(chrome.runtime.sendMessage({action:"deletePossiblePassword"}),window.onload=function(){var a=document.querySelectorAll("div[role=button]"),a=a[a.length-1];a.addEventListener("click",R,!0);a.addEventListener("keydown",function(a){32==a.keyCode&&R()},!0);document.addEventListener("keydown",function(a){13==a.keyCode&&R()},
!0)}):(!S()&&ea()&&chrome.runtime.sendMessage({action:"looksLikeGoogle",url:k,referer:M,securityEmailAddress:F}),chrome.runtime.sendMessage({action:"savePossiblePassword"}));chrome.runtime.sendMessage({action:"statusRequest"},function(a){N=!1;T(a)})}},T=function(a){a=JSON.parse(a);if(a.passwordLengths&&(G=a.passwordLengths,0==G.length)){N=!1;return}A&&l(A)||l("https://accounts.google.com/")||S()?N=!1:(N=!0,O||chrome.storage.local.get("allowed_hosts",function(a){var c=window.location.origin;0<Object.keys(a).length&&
a.allowed_hosts[c]&&(N=!1)}),V())},W=function(a){N&&a.isTrusted&&chrome.runtime.sendMessage({action:"handleKeypress",keyCode:a.charCode,typedTimeStamp:a.timeStamp,url:k,referer:M,looksLikeGoogle:V()})};h("passwordalert.handleKeypress",W);var X=function(a){N&&a.isTrusted&&chrome.runtime.sendMessage({action:"handleKeydown",keyCode:a.keyCode,shiftKey:a.shiftKey,typedTimeStamp:a.timeStamp,url:k,referer:M,looksLikeGoogle:V()})};h("passwordalert.handleKeydown",X);
var Y=function(a){!N||void 0===a.clipboardData||a.timeStamp<=H||(H=a.timeStamp,chrome.runtime.sendMessage({action:"checkString",password:a.clipboardData.getData("text/plain").trim(),url:k,referer:M,looksLikeGoogle:V()}))};h("passwordalert.handlePaste",Y);
var ca=function(){var a;a=document.querySelector(D);var b=document.querySelector(C);a&&!a.value||b&&!b.value?(console.log("SSO data is not filled in."),a=!1):a=!0;a&&(a=document.querySelector(D).value,b=document.querySelector(C).value,-1==a.indexOf("@")&&(a+="@"+E.split(",")[0].trim()),chrome.runtime.sendMessage({action:"setPossiblePassword",email:a,password:b}))},da=function(){var a=document.getElementById("gaia_loginform"),b=a.Email?p(a.Email.value.toLowerCase()):"",a=a.Passwd?a.Passwd.value:"",
c;if(c=O){var d;a:{c=E.split(",");for(d in c)if(m(b,"@"+c[d].trim())){d=!0;break a}d=!1}c=!d}c||0==(null==a?"":String(a)).length||chrome.runtime.sendMessage({action:"setPossiblePassword",email:b,password:a})},R=function(){var a=Date.now();window.onbeforeunload=function(){if(!(1E3<Date.now()-a)){for(var b=document.querySelector("div[data-config]").getAttribute("data-config"),c=b.indexOf('",["')+4,b=b.substring(c,b.indexOf('"',c)),d=c="",e=0;e<b.length;){var g;g=b.charAt(e);var v='"<(['.indexOf(g);
if(-1!=v&&!z(b,e)){for(var v='">)]'.charAt(v),t=b.indexOf(v,e+1);0<=t&&z(b,t);)t=b.indexOf(v,t+1);g=0<=t?b.substring(e,t+1):g}"<"==g.charAt(0)&&-1!=g.indexOf(">")?d=g.substring(1,g.indexOf(">")):""==d&&(c+=g);e+=g.length}""==d&&-1!=c.indexOf("@")&&(d=c,c="");c=n(c);c=q(c,"'");c=q(c,'"');c=c.replace(w,'"');c=c.replace(y,"\\");d=n(d);c=new r(d,c);aa.test(c.a)?chrome.runtime.sendMessage({action:"setPossiblePassword",email:b,password:document.querySelector('input[aria-label="New password"]').value}):
console.log("Parsed email on change password page is not valid: %s",b)}}},V=function(){if(1==I||0==I)return I;var a=document.documentElement.innerHTML.slice(0,12E4),b;for(b in J)if(0<=a.indexOf(J[b]))return I=!0;return I=!1},ea=function(){var a=document.documentElement.innerHTML.slice(0,12E4),b;for(b in K)if(0<=a.indexOf(K[b]))return!0;return!1},S=function(){var a;a=((a=k.match(ba)[3]||null)?decodeURI(a):a)||"";for(var b in L)if(m(a,L[b]))return!0;return!1};
chrome.storage.onChanged.addListener(function(a,b){if("managed"==b){b=function(a,b){return a.filter(function(a){return 0>b.indexOf(a)})};for(var c in a){O||(O=!0);var d=a[c].newValue,e=a[c].oldValue;switch(c){case "corp_email_domain":E=d.replace(/@/g,"").toLowerCase();break;case "corp_html":J=b(J,e);Array.prototype.push.apply(J,d);break;case "corp_html_tight":K=b(K,e);Array.prototype.push.apply(K,d);break;case "security_email_address":F=d;break;case "sso_form_selector":B=d;break;case "sso_password_selector":C=
d;break;case "sso_url":A=d;break;case "sso_username_selector":D=d;break;case "whitelist_top_domains":L=b(L,e),Array.prototype.push.apply(L,d)}}}});
(function(a){chrome.storage.managed.get(function(b){0==Object.keys(b).length?O=!1:(O=!0,E=b.corp_email_domain.replace(/@/g,"").toLowerCase(),F=b.security_email_address,B=b.sso_form_selector,C=b.sso_password_selector,A=b.sso_url,D=b.sso_username_selector,b.whitelist_top_domains&&Array.prototype.push.apply(L,b.whitelist_top_domains),b.corp_html&&Array.prototype.push.apply(J,b.corp_html),b.corp_html_tight&&Array.prototype.push.apply(K,b.corp_html_tight));P=!0;a()})})(U);
window.addEventListener("keypress",W,!0);window.addEventListener("keydown",X,!0);window.addEventListener("paste",Y,!0);var Z=location.href.toString();"about:blank"==Z?(k=window.parent.location.href,M=""):(k=Z,M=document.referrer.toString());chrome.runtime.onMessage.addListener(function(a){N=!1;T(a)});document.addEventListener("DOMContentLoaded",function(){Q=!0;U()});if("interactive"==document.readyState||"complete"==document.readyState||"loaded"==document.readyState)Q=!0,U();
