import 'jasmine';
import {Builder, By, Capabilities, WebDriver} from 'selenium-webdriver';

/**
 * Metadata file generated by `rules_webtesting` for browser tests.
 * The metadata provides configuration for launching the browser and
 * necessary capabilities. See source for details:
 * https://github.com/bazelbuild/rules_webtesting/blob/06023bb3/web/internal/metadata.bzl#L69-L82
 */
interface WebTestMetadata {
  capabilities: Capabilities;
}

if (process.env['WEB_TEST_METADATA'] === undefined) {
  console.log(`Test running outside of a "web_test" target. No browser found.`);
  process.exit(1);
}

const runfiles = require(process.env['BAZEL_NODE_RUNFILES_HELPER']!);
const webTestMetadata: WebTestMetadata =
    require(runfiles.resolve(process.env['WEB_TEST_METADATA']));

describe('wait for Angular', () => {
  let wd: WebDriver;

  beforeAll(async () => {
    wd = await new Builder()
      .usingServer(process.env.WEB_TEST_WEBDRIVER_SERVER!)
      .withCapabilities(webTestMetadata.capabilities)
      .build();
  });

  afterAll(async () => {
    await wd.quit();
  });

  it('works', async () => {
    await wd.get('https://material.angular.io');
    const header = await wd.findElement(By.css('.mat-h1'));
    console.error(await wd.executeScript('return navigator.userAgent'));
    expect(await header.getText()).toBe('Angular Matedrial');
  });
});
