import {spawn} from 'child_process';
import {existsSync, statSync, copySync} from 'fs-extra';
import {join} from 'path';
import {task, src, dest} from 'gulp';
import {execTask} from '../util/task_helpers';
import {DIST_RELEASE, DIST_BUNDLES, DIST_MATERIAL} from '../constants';

// There are no type definitions available for these imports.
import gulpRunSequence = require('run-sequence');
import minimist = require('minimist');

const argv = minimist(process.argv.slice(3));

// Capture all d.ts files output by typescript compilation except for the special files
// generated by ngc.
const typingsGlob = [
  join(DIST_MATERIAL, '**', '*.d.ts'),
  `!${join(DIST_MATERIAL, 'index.d.ts')}`,
  `!${join(DIST_MATERIAL, 'public_api.d.ts')}`,
];

// Capture all UMD bundles.
const umdGlob = join(DIST_BUNDLES, '*.umd.*');

// Capture all flat ESM bunldes (e.g., "material.js" and "material.es5.js")
const fesmGlob = [join(DIST_BUNDLES, "*.js"), `!${umdGlob}`];

task('build:release', function(done: () => void) {
  gulpRunSequence(
    'library:build',
    ':package:release',
    done
  );
});

/** Task that combines intermediate build artifacts into the release package structure. */
task(':package:release', [
  ':package:metadata',
  ':package:typings',
  ':package:umd',
  ':package:fesm',
]);

/** Copy metatadata.json and associated d.ts files to the root of the package structure. */
task(':package:metadata', () => {
  // https://github.com/angular/angular/blob/master/build.sh#L293-L294
  copySync(join(DIST_MATERIAL, 'public_api.d.ts'), join(DIST_RELEASE, 'public_api.d.ts'));
  copySync(join(DIST_MATERIAL, 'index.d.ts'), join(DIST_RELEASE, 'material.d.ts'));
  copySync(join(DIST_MATERIAL, 'index.metadata.json'),
      join(DIST_RELEASE, 'material.metadata.json'));
});

/** Copy all d.ts except the special flat typings from ngc to typings/ in the release package. */
task(':package:typings', () => src(typingsGlob).pipe(dest(join(DIST_RELEASE, 'typings'))));

/** Copy umd bundles to the root of the release package. */
task(':package:umd', () => src(umdGlob).pipe((dest(join(DIST_RELEASE, 'bundles')))));

/** Copy fesm bundles to @angular/material in the release package */
task(':package:fesm', () => src(fesmGlob).pipe(dest(join(DIST_RELEASE, '@angular', 'material'))));

/** Make sure we're logged in. */
task(':publish:whoami', execTask('npm', ['whoami'], {
  silent: true,
  errMessage: 'You must be logged in to publish.'
}));

task(':publish:logout', execTask('npm', ['logout']));


function _execNpmPublish(label: string): Promise<{}> {
  const packageDir = DIST_RELEASE;
  if (!statSync(packageDir).isDirectory()) {
    return;
  }

  if (!existsSync(join(packageDir, 'package.json'))) {
    throw new Error(`"${packageDir}" does not have a package.json.`);
  }

  if (!existsSync(join(packageDir, 'LICENSE'))) {
    throw new Error(`"${packageDir}" does not have a LICENSE file`);
  }

  process.chdir(packageDir);
  console.log(`Publishing material...`);

  const command = 'npm';
  const args = ['publish', '--access', 'public', label ? `--tag` : undefined, label || undefined];
  return new Promise((resolve, reject) => {
    console.log(`  Executing "${command} ${args.join(' ')}"...`);
    if (argv['dry']) {
      resolve();
      return;
    }

    const childProcess = spawn(command, args);
    childProcess.stdout.on('data', (data: Buffer) => {
      console.log(`  stdout: ${data.toString().split(/[\n\r]/g).join('\n          ')}`);
    });
    childProcess.stderr.on('data', (data: Buffer) => {
      console.error(`  stderr: ${data.toString().split(/[\n\r]/g).join('\n          ')}`);
    });

    childProcess.on('close', (code: number) => {
      if (code == 0) {
        resolve();
      } else {
        reject(new Error(`Material did not publish, status: ${code}.`));
      }
    });
  });
}

task(':publish', function(done: (err?: any) => void) {
  const label = argv['tag'];
  const currentDir = process.cwd();

  if (!label) {
    console.log('You can use a label with --tag=labelName.');
    console.log('Publishing using the latest tag.');
  } else {
    console.log(`Publishing using the ${label} tag.`);
  }
  console.log('\n\n');

  // Publish only the material package.
  return _execNpmPublish(label)
    .then(() => done())
    .catch((err: Error) => done(err))
    .then(() => process.chdir(currentDir));
});

task('publish', function(done: () => void) {
  gulpRunSequence(
    ':publish:whoami',
    'build:release',
    ':publish',
    ':publish:logout',
    done
  );
});
