export {CdkTabsConfigurableExample} from './cdk-tabs-configurable/cdk-tabs-configurable-example';
export {CdkTabsExplicitSelectionExample} from './cdk-explicit-selection/cdk-tabs-explicit-selection-example';
export {CdkTabsSelectionFollowsFocusExample} from './cdk-selection-follows-focus/cdk-tabs-selection-follows-focus-example';
export {CdkTabsVerticalExample} from './cdk-vertical-orientation/cdk-tabs-vertical-example';
export {CdkTabsRtlExample} from './cdk-rtl/cdk-tabs-rtl-example';
export {CdkTabsActiveDescendantExample} from './cdk-active-descendant/cdk-tabs-active-descendant-example';
export {CdkTabsDisabledFocusableExample} from './cdk-disabled-focusable/cdk-tabs-disabled-focusable-example';
export {CdkTabsDisabledSkippedExample} from './cdk-disabled-skipped/cdk-tabs-disabled-skipped-example';
export {CdkTabsDisabledExample} from './cdk-disabled/cdk-tabs-disabled-example';
