import {CommitMessageConfig} from '@angular/ng-dev';

/**
 * The configuration for `ng-dev commit-message` commands.
 */
export const commitMessage: CommitMessageConfig = {
  maxLineLength: Infinity,
  minBodyLength: 0,
  minBodyLengthTypeExcludes: ['docs'],
  scopes: [
    'multiple', // For when a commit applies to multiple components.
    'cdk-experimental/column-resize',
    'cdk-experimental/combobox',
    'cdk-experimental/popover-edit',
    'cdk-experimental/scrolling',
    'cdk-experimental/selection',
    'cdk-experimental/table-scroll-container',
    'cdk/a11y',
    'cdk/accordion',
    'cdk/bidi',
    'cdk/clipboard',
    'cdk/coercion',
    'cdk/collections',
    'cdk/dialog',
    'cdk/drag-drop',
    'cdk/keycodes',
    'cdk/layout',
    'cdk/listbox',
    'cdk/menu',
    'cdk/observers',
    'cdk/overlay',
    'cdk/platform',
    'cdk/portal',
    'cdk/schematics',
    'cdk/scrolling',
    'cdk/stepper',
    'cdk/table',
    'cdk/testing',
    'cdk/text-field',
    'cdk/tree',
    'google-maps',
    'material-experimental/column-resize',
    'material-experimental/theming-next',
    'material-experimental/theming',
    'material-experimental/menubar',
    'material-experimental/popover-edit',
    'material-experimental/selection',
    'material/button',
    'material/card',
    'material/checkbox',
    'material/dialog',
    'material/form-field',
    'material/input',
    'material/paginator',
    'material/progress-bar',
    'material/progress-spinner',
    'material/slide-toggle',
    'material/snack-bar',
    'material/table',
    'material/tabs',
    'material/autocomplete',
    'material/badge',
    'material/bottom-sheet',
    'material/button-toggle',
    'material/chips',
    'material/core',
    'material/datepicker',
    'material/divider',
    'material/expansion',
    'material/form-field',
    'material/grid-list',
    'material/icon',
    'material/list',
    'material/menu',
    'material/prebuilt-themes',
    'material/radio',
    'material/schematics',
    'material/select',
    'material/sidenav',
    'material/slider',
    'material/sort',
    'material/stepper',
    'material/testing',
    'material/theming',
    'material/toolbar',
    'material/tooltip',
    'material/tree',
    'material-moment-adapter',
    'material-date-fns-adapter',
    'material-luxon-adapter',
    'youtube-player',
  ],
};
