/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */

import {Directionality} from '@angular/cdk/bidi';
import {FullscreenOverlayContainer, OverlayContainer} from '@angular/cdk/overlay';
import {HttpClientModule} from '@angular/common/http';
import {NgModule, NgModuleFactoryLoader, ɵNgModuleFactory} from '@angular/core';
import {MAT_RIPPLE_GLOBAL_OPTIONS} from '@angular/material';
import {BrowserModule} from '@angular/platform-browser';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {RouterModule} from '@angular/router';
import {DevAppComponent} from './dev-app';
import {DevAppDirectionality} from './dev-app/dev-app-directionality';
import {DevAppModule} from './dev-app/dev-app-module';
import {DEV_APP_ROUTES} from './dev-app/routes';
import {DevAppRippleOptions} from './ripple/ripple-options';

declare function require(deps: string[], callback: (exports: any) => void): void;

/**
 * RequireJS module loader that loads AMD chunk files generated by rollup. Additionally does
 * not look for a ".factory" file as with Ivy factory files are not generated by default.
 * Workaround until: https://github.com/angular/angular/pull/28685 landed.
 */
const requireJsModuleLoader: NgModuleFactoryLoader = {
  load: (path: string) => {
    const [chunkPath, exportName] = path.split('#');
    return new Promise(resolve => {
      require([chunkPath], e => resolve(new ɵNgModuleFactory(e[exportName])));
    });
  }
};

@NgModule({
  imports: [
    BrowserAnimationsModule,
    BrowserModule,
    DevAppModule,
    HttpClientModule,
    RouterModule.forRoot(DEV_APP_ROUTES),
  ],
  declarations: [
    DevAppComponent,
  ],
  providers: [
    {provide: OverlayContainer, useClass: FullscreenOverlayContainer},
    {provide: MAT_RIPPLE_GLOBAL_OPTIONS, useExisting: DevAppRippleOptions},
    {provide: Directionality, useClass: DevAppDirectionality},
    {provide: NgModuleFactoryLoader, useValue: requireJsModuleLoader},
  ],
  bootstrap: [DevAppComponent],
})
export class MainModule {
}
