load("//tools:defaults.bzl", "ng_module")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "scrollable-table-body",
    srcs = glob(["**/*.ts"]),
    deps = [
        "//src/components-examples/cdk-experimental/scrollable-table-body",
        "//src/components-examples/material-experimental/scrollable-table-body",
        "//src/dev-app/example",
        "@npm//@angular/forms",
        "@npm//@angular/router",
    ],
)
