name: 'CI (material.angular.dev)'

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Execute Build
        run: pnpm --silent build //docs/...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Execute Tests
        run: pnpm bazel test --test_tag_filters=-e2e,-audit //docs/...
      - name: Store Test Logs
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        if: always()
        with:
          name: test-logs
          path: material.angular.dev/bazel-testlogs/
          retention-days: 14

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@3b181b7da71ce256d7dc44532ed3df8198f7d853 # main
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Execute Lighthouse Audit
        run: pnpm --silent bazel test --test_tag_filters=audit //docs/...
      - name: Store Audit Logs
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        if: always()
        with:
          name: lighthouse-logs
          path: material.angular.dev/bazel-testlogs/
          retention-days: 14
