name: 'PR (material.angular.dev)'

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Execute Build
        run: pnpm bazel build //docs/...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Execute Tests
        run: pnpm bazel test --test_tag_filters=-e2e,-audit //docs/...
      - name: Store Test Logs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-logs
          path: material.angular.dev/bazel-testlogs/
          retention-days: 14

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Setup Bazel
        uses: angular/dev-infra/github-actions/bazel/setup@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Setup Bazel RBE
        uses: angular/dev-infra/github-actions/bazel/configure-remote@ba726e7bca0b08b125ccc6f93c233749e1213c17
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Execute Lighthouse Audit
        run: pnpm bazel test --test_tag_filters=audit //docs/...
      - name: Store Audit Logs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: lighthouse-logs
          path: material.angular.dev/bazel-testlogs/
          retention-days: 14
